/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BpButtonComp: typeof import('./components/BpButton/BpButtonComp.vue')['default']
    BpLoad: typeof import('./components/BpLoad/index.vue')['default']
    BpLoadComp: typeof import('./components/BpLoad/BpLoadComp.vue')['default']
    BpSwiperComp: typeof import('./components/BpSwiper/BpSwiperComp.vue')['default']
    BpTab: typeof import('./components/BpTab/index.vue')['default']
    CountDown: typeof import('./components/CountDown/index.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ItemsPop: typeof import('./components/ItemsPop/index.vue')['default']
    LangCollapse: typeof import('./components/TopBar/LangCollapse.vue')['default']
    Menu: typeof import('./components/TopBar/Menu.vue')['default']
    Progress: typeof import('./components/Progress/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/TopBar/index.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
    WalletBtn: typeof import('./components/WalletBtn/index.vue')['default']
  }
}
